- hosts: ustudy
  gather_facts: no
  become: yes
  ignore_unreachable: yes

  tasks:

              - name: create cron job
                cron:
                  name: auto-sc
                  minute: "*/5"
                  job: /bin/bash /home/ustudy/scripts/auto-sc.sh
 
