- name: MESTO NA DISKE
  hosts: ustudy
  gather_facts: no
  become: yes
  ignore_unreachable: yes


  tasks:
    - name: Vypolnenie komandy df -h
      shell: /bin/bash /home/ustudy/scripts/svod_pamyati.sh  
      register: disk_space
      changed_when: false

    - name: Vyvod svobodnogo pamyati
      debug:
        var: disk_space.stdout_lines

#    - name: copy vars to file
#      copy:
#        content: "{{ disk_space.stdout_lines }}"
#        dest: "/tmp/{{ ansible_date_time.date }}.txt"
